### ISSUE TITLE
Is libsimple_tacacct is compatible with Ubuntu 22.04?Giving error # multiarch-support is not installed.

### ISSUE THREAD

**Issue by knight-on-work** [daveolson53/libsimple-tacacct#1]
Error Log:
dpkg -i ./libsimple-tacacct1_1.0.2-1_amd64.deb
dpkg: regarding .../libsimple-tacacct1_1.0.2-1_amd64.deb containing libsimple-tacacct1, pre-dependency problem:
 libsimple-tacacct1 pre-depends on multiarch-support
  multiarch-support is not installed.

dpkg: error processing archive ./libsimple-tacacct1_1.0.2-1_amd64.deb (--install):
 pre-dependency problem - not installing libsimple-tacacct1
Errors were encountered while processing:
 ./libsimple-tacacct1_1.0.2-1_amd64.deb
Please help if anyone successfully install this deb package on ubuntu 22.04?

**Comment by daveolson53** [comment]
Probably not compatible without updating.  I'm retired, and will not be working on this set of issues.
